% Create a helix antenna
% Generated by MATLAB(R) 9.8 and Antenna Toolbox 4.2.
% Generated on: 13-Feb-2021 18:51:01

%% Antenna Properties 
% Design antenna at frequency 2400000000Hz
antennaObject = design(helix,2400000000);
% Properties changed 
antennaObject.Radius = 0.018175;
antennaObject.Width = 0.001445;
antennaObject.Turns = 8.3304;
antennaObject.Spacing = 0.034876;
% show for helix
figure;
show(antennaObject) 

