<?xml version="1.0" ?>
<LIBRARIES>
	<LIBRARY>
		<NAME>MHT2012N_Level1_Rev0_DK</NAME>
		<CATEGORY>DL</CATEGORY>
		<SUBLIBRARY>
			<NAME>LDMOSFET</NAME>
			<RECORD_FILES>MHT2012N.rec</RECORD_FILES>
		</SUBLIBRARY>
	</LIBRARY>
</LIBRARIES>
